# Generated by Django 4.1 on 2022-08-16 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_comment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
